In [1]:
import pandas as pd
import numpy as np
from pandas_summary import DataFrameSummary
from sklearn.preprocessing import LabelEncoder, Imputer, StandardScaler

In [2]:
df = pd.read_feather('all_preprocessed.fth')

In [3]:
df.columns

Index(['Store', 'DayOfWeek', 'Date', 'Sales', 'Customers', 'Open', 'Promo',
       'StateHoliday', 'SchoolHoliday', 'Year', 'Month', 'Week', 'Day',
       'StoreType', 'Assortment', 'CompetitionDistance',
       'CompetitionOpenSinceMonth', 'CompetitionOpenSinceYear', 'Promo2',
       'Promo2SinceWeek', 'Promo2SinceYear', 'PromoInterval', 'State', 'file',
       'week', 'trend', 'Date_y', 'Month_y', 'Day_y', 'file_DE', 'week_DE',
       'trend_DE', 'Date_DE', 'State_DE', 'Month_DE', 'Day_DE', 'file_y',
       'Max_TemperatureC', 'Mean_TemperatureC', 'Min_TemperatureC',
       'Dew_PointC', 'MeanDew_PointC', 'Min_DewpointC', 'Max_Humidity',
       'Mean_Humidity', 'Min_Humidity', 'Max_Sea_Level_PressurehPa',
       'Mean_Sea_Level_PressurehPa', 'Min_Sea_Level_PressurehPa',
       'Max_VisibilityKm', 'Mean_VisibilityKm', 'Min_VisibilitykM',
       'Max_Wind_SpeedKm_h', 'Mean_Wind_SpeedKm_h', 'Max_Gust_SpeedKm_h',
       'Precipitationmm', 'CloudCover', 'Events', 'WindDirDegrees',
       

## Categorical vars

In [4]:
cat_vars = ['Store', 'DayOfWeek', 'Year', 'Month', 'Day', 'StateHoliday', 'CompetitionMonthsOpen', 'Promo2Weeks', 
            'StoreType', 'Assortment', 'PromoInterval', 'CompetitionOpenSinceYear', 'Promo2SinceYear', 'State', 
            'Week', 'Events', 'Promo_fw', 'Promo_bw', 'StateHoliday_fw', 'StateHoliday_bw', 'SchoolHoliday_fw', 'SchoolHoliday_bw']

In [5]:
DataFrameSummary(df[cat_vars]).summary().loc[['uniques', 'types']]

Store DayOfWeek     Year    Month      Day StateHoliday  \
uniques     1115         7        3       12       31            2   
types    numeric   numeric  numeric  numeric  numeric         bool   

        CompetitionMonthsOpen Promo2Weeks    StoreType   Assortment  ...  \
uniques                    25          26            4            3  ...   
types                 numeric     numeric  categorical  categorical  ...   

        Promo2SinceYear        State     Week       Events Promo_fw Promo_bw  \
uniques               8           12       52           21        6        6   
types           numeric  categorical  numeric  categorical  numeric  numeric   

        StateHoliday_fw StateHoliday_bw SchoolHoliday_fw SchoolHoliday_bw  
uniques               3               3                8                8  
types           numeric         numeric          numeric          numeric  

[2 rows x 22 columns]

In [6]:
# Reemplaza nulls por "" en categoricas
for v in cat_vars: df.loc[df[v].isnull(), v] = ""

# Continuos Vars

In [7]:
contin_vars = ['CompetitionDistance', 
   'Max_TemperatureC', 'Mean_TemperatureC', 'Min_TemperatureC',
   'Max_Humidity', 'Mean_Humidity', 'Min_Humidity', 'Max_Wind_SpeedKm_h', 
   'Mean_Wind_SpeedKm_h', 'CloudCover', 'trend', 'trend_DE',
   'AfterStateHoliday', 'BeforeStateHoliday', 'Promo', 'SchoolHoliday']

In [8]:
# Reemplaza nulls por 0 en continuas
for v in contin_vars: df.loc[df[v].isnull(), v] = 0

# Normalización en continuas y LabelEncode en Categoricas

In [9]:
from sklearn_pandas import DataFrameMapper

In [10]:
cat_maps = [(o, LabelEncoder()) for o in cat_vars]
contin_maps = [([o], StandardScaler()) for o in contin_vars]

In [11]:
mapper_cat = DataFrameMapper(cat_maps)
map_cat_fit = mapper_cat.fit(df)

In [12]:
# Assortment es la novena posición en cat_maps
N = 15
print(df['Assortment'].values[:N])
print(mapper_cat.transform(df)[:, 9][:N])

['a' 'a' 'a' 'c' 'a' 'a' 'c' 'a' 'c' 'a' 'c' 'c' 'a' 'a' 'c']
[0 0 0 2 0 0 2 0 2 0 2 2 0 0 2]


In [13]:
mapper_cont = DataFrameMapper(contin_maps)
map_cont_fit = mapper_cont.fit(df)

In [14]:
N = 10
print(df['CompetitionDistance'].values[:N])
print(map_cont_fit.transform(df)[:, 0][:N])

[ 1270.   570. 14130.   620. 29910.   310. 24000.  7520.  2030.  3160.]
[-0.53772351 -0.62851175  1.13018633 -0.62202688  3.17681286 -0.6622331
  2.41030064  0.27288586 -0.43915341 -0.29259523]


In [15]:
df[cat_vars] = mapper_cat.transform(df)

In [16]:
df[contin_vars] = mapper_cont.transform(df)

In [17]:
df.head()

Store  DayOfWeek       Date  Sales  Customers  Open     Promo  \
0      0          4 2015-07-31   5263        555     1  1.273237   
1      1          4 2015-07-31   6064        625     1  1.273237   
2      2          4 2015-07-31   8314        821     1  1.273237   
3      3          4 2015-07-31  13995       1498     1  1.273237   
4      4          4 2015-07-31   4822        559     1  1.273237   

   StateHoliday  SchoolHoliday  Year  ...  AfterStateHoliday  \
0             0       2.144211     2  ...           0.644376   
1             0       2.144211     2  ...           0.965073   
2             0       2.144211     2  ...           0.644376   
3             0       2.144211     2  ...           0.965073   
4             0       2.144211     2  ...           0.644376   

   BeforeStateHoliday  AfterPromo  BeforePromo  SchoolHoliday_bw  \
0            1.072424           0            0                 5   
1            1.072424           0            0                 5   
2            1.072424           0            0                 5   
3            1.072424           0            0                 5   
4            1.072424           0            0                 5   

   StateHoliday_bw  Promo_bw  SchoolHoliday_fw  StateHoliday_fw  Promo_fw  
0                0         5                 1                0         1  
1                0         5                 1                0         1  
2                0         5                 1                0         1  
3                0         5                 1                0         1  
4                0         5                 1                0         1  

[5 rows x 80 columns]

In [18]:
DataFrameSummary(df[cat_vars]).summary().loc[['uniques', 'types']]

Store DayOfWeek     Year    Month      Day StateHoliday  \
uniques     1115         7        3       12       31            2   
types    numeric   numeric  numeric  numeric  numeric         bool   

        CompetitionMonthsOpen Promo2Weeks StoreType Assortment  ...  \
uniques                    25          26         4          3  ...   
types                 numeric     numeric   numeric    numeric  ...   

        Promo2SinceYear    State     Week   Events Promo_fw Promo_bw  \
uniques               8       12       52       22        6        6   
types           numeric  numeric  numeric  numeric  numeric  numeric   

        StateHoliday_fw StateHoliday_bw SchoolHoliday_fw SchoolHoliday_bw  
uniques               3               3                8                8  
types           numeric         numeric          numeric          numeric  

[2 rows x 22 columns]

In [19]:
df['Assortment'][:10].values

array([0, 0, 0, 2, 0, 0, 2, 0, 2, 0])

# Final processing

In [20]:
df.shape

(1017209, 80)

In [21]:
df_sales = df[df.Sales!=0]

In [22]:
df_sales.shape

(844338, 80)

In [26]:
df_sales.reset_index(inplace=True)

In [27]:
df_sales.to_feather('normalized_data.fth')